### PR TITLE
feat: add vitesse black theme

### PR DESCRIPTION
**Pull request by Daydreamer-riri**
Hi @illixion , I want to know if there is a way to preview the effect so that I can make some adjustments.

### CODE REVIEW

**Comment by illixion** [comment]
I've just pushed v1.1.23 which includes a new "Custom theme" option to enable local previewing of themes. Simply change the Vibrancy theme to "Custom theme (use imports)" and load your CSS file using the `vscode_vibrancy.imports` setting, or refer to this guide for more info: https://github.com/illixion/vscode-vibrancy-continued/blob/master/themes/README.md.

Let me know if you encounter any issues and when I can merge your PR.

**Comment by Daydreamer-riri** [comment]
grateful! I will adjust this theme as soon as possible.

**Comment by Daydreamer-riri** [comment]
grateful! I will adjust this theme as soon as possible.

**Comment by illixion** [comment]
Closing this PR due to inactivity, please re-open once your theme is adjusted and ready to be merged

**Pull request closed without merging**
