### PR TITLE
:bug: fix(inject): load local resource

### PR DESCRIPTION
**Pull request by frg2089**
not allowed to load local resource.
the URL should be started by 'vscode-file://vscode-app/'

I have not tested this and it may not work.

### CODE REVIEW

**Comment by illixion** [comment]
Thanks for the contribution, will test this and merge if there are no issues.

**Comment by frg2089** [comment]
well, I got an error when I test it.
```
ERR XHR failed: Download: XHR failed
```

**Comment by frg2089** [comment]
> well, it does not worked when I test it.

I was wrong, it was working.

The thing to note is that there must be only one space between `vscode-app` and the path, and it must be the `/` symbol and not the `\` symbol. 

`vscode-file://vscode-app/path/to/file`

**Comment by illixion** [comment]
I’ve actually tried using your solution while I was trying to fix this bug, and it did work, but there was still a CSP rule preventing loading JS/CSS files from outside of the app’s folders. I went for a different solution instead, where Vibrancy will read the JS/CSS contents directly and embed them in `style`/`script` tags, which seems to work just as well.

**Pull request closed without merging**
